### ISSUE TITLE
Dash (/) in automatic file names

### ISSUE THREAD

**Issue by palmtop** [m6h/front-dl#3]
For example in the following video: https://www.youtube.com/watch?v=CXU7Xlf8wTI there is a / in the author, which is brought to the file name, and it is downloaded to a separate directory.

**Comment by m6h** [comment]
Ah yes i see what you mean. Fixed in latest build `m60h/front-dl:0194acb7` or newer. Simply replaces forward slashes `/` in file name with an underscore `_`
